### PR TITLE
Directory node cleanup 9

### LINKED ISSUE #9: directory node cleanup
In accordance with our in-person discussions about the functionality expected of the directory node, I will be removing and adding various bits of code from `directory/directory.py`.  Specifically:

Removing:
* anything related to 'circuit numbers' since we won't be needing those
* any crypto-related method stubs.  we are not yet sure of the architecture of our application, such as how the crypto functionality will work and be incorporated into the rest of the software.  The existing stubs either make assumptions about the architecture or just occupy space on the page, visual distraction.
* the `network.conf` file.  I believe all the params within it should just be declared as globals in `directory.py` for clarity and simplicity.

Adding:
* finishing up the directory node so that it implements the 'directory node protocol' as discussed.  These changes will be elaborated on in the PR.

### PR DESCRIPTION
**Pull request by stumash**
resolves #9

Ok, I did a lot of stuff.. definitely outside of the scope of the issue description for #9.  Forgiveness appreciated.

1. I made a dummy `onion_router.py`.  It accepts connections, receives some text, calls `.upperCase()` on the text, send the upper case text back and closes the connection.  I did this just to test the `ping_node` functionality in `directory.py` where the directory node tests various onion routers to see if they're up and running. I stole this from @CamiloGarciaLaRotta's `doodles` branch.
2. I "cleaned" `directory.py`.  not many real changes in *how* it works, just moved around some stuff, trimmed, ... .  Now, it polls the network for a list of active onion routers, gets their pubkeys (method stub for now), and then you can say something to it and it will respond with a path (with pubkeys) through the onion network it knows about.
3. I wrote a bunch of scripts for deploying+running and killing the `directory.py` and `onion_router.py` processes for the server:port combos found [in the Dev-Tips wiki page](/CamiloGarciaLaRotta/Cebolla/wiki/Dev-Tips).  The scripts are all described [in the Scripts wiki page](/CamiloGarciaLaRotta/Cebolla/wiki/Scripts) I wrote.

### CODE REVIEW

**Comment by stumash** [comment]
I want everyone to see this PR (including testers), mainly to look at the [Scripts wiki page](/CamiloGarciaLaRotta/Cebolla/wiki/Scripts)

**Comment by DestructiveReasoning** [comment]
I just finished reading through the commits. For the most part, everything looks pretty good. Nice script wiki and documentation in the code. I have a few questions to go over during the meeting today but nothing too severe.

**Review by CamiloGarciaLaRotta — APPROVED** [review]
Good to Go

**Comment by dliuproduction** [comment]
Deploy and shutdown scripts for onion_router and directory working well. I tested the onion_router on lab2-NN.cs.mcgill.ca and the onion_router.py on there returns the uppercase messages as intended.

**Pull request merged**
